
#------------------------------------------------s6
---
- name: Установка MongoDB на Ubuntu
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Импортировать публичный ключ MongoDB
      ansible.builtin.apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 7F0CEB10
        state: present

    - name: Добавить репозиторий MongoDB
      ansible.builtin.apt_repository:
        repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
        state: present

    - name: Обновить кеш пакетов
      ansible.builtin.apt:
        update_cache: yes

    - name: Установить пакет mongodb-org
      ansible.builtin.apt:
        name: mongodb-org
        state: latest

    - name: Запустить и включить сервис mongod
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
