
---
  
    - name: Импортировать данные в MongoDB с помощью mongoimport
      shell: >
        mongoimport --db {{ db_name }} --collection {{ collection_name }}
        --file bdjsondump.txt --jsonArray --drop
      