
# tasks file for mysqldump
#------------------------------------------------s7
---

    - name: Создать базу данных и коллекцию в MongoDB
      shell: >
        mongo --eval "use {{ db_name }}; db.createCollection({{ collection_name }});"
      args:
        warn: false
  
    - name: Импортировать данные в MongoDB с помощью mongoimport
      shell: >
        mongoimport --db {{ db_name }} --collection {{ collection_name }}
        --file bdjsondump.txt --jsonArray --drop
      args:
        warn: false